### ISSUE TITLE
Unable to install with yarn

### ISSUE THREAD

**Issue by nbabaka2023** [Brooooooklyn/keyring-node#46]
Hi!

I was unable to install it with yarn

Couldn't find package "@napi-rs/keyring-android-arm64@1.1.4" required by "@napi-rs/keyring" on the "npm" registry
Couldn't find package "@napi-rs/keyring-android-arm-eabi@1.1.4" required by "@napi-rs/keyring" on the "npm" registry.

Thank you!

**Comment by Brooooooklyn** [comment]
Fixed in https://github.com/Brooooooklyn/keyring-node/releases/tag/v1.1.5

**Comment by altinokdarici** [comment]
I'm hitting the same issue with 1.1.5. It seems like those missing packages are still missing on npm feed.

error Couldn't find package "@napi-rs/keyring-android-arm64@1.1.5" required by "@napi-rs/keyring@*" on the "npm" registry.
error Couldn't find package "@napi-rs/keyring-android-arm64@1.1.5" required by "@napi-rs/keyring@^1.1.5" on the "npm" registry.

**Comment by Brooooooklyn** [comment]
Try this version: https://github.com/Brooooooklyn/keyring-node/releases/tag/v1.1.6
